# CMake CI Test Workflow
#
# This workflow tests the artagon-workflows CMake C/C++ CI reusable workflows.
# It validates that the workflows behave correctly with various configurations.

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Run daily at 2 AM UTC to catch any breaking changes in artagon-workflows
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      c-standard:
        description: 'C standard to test'
        required: false
        default: '17'
      cpp-standard:
        description: 'C++ standard to test'
        required: false
        default: '20'
  repository_dispatch:
    types: [workflow-updated, release-published]

jobs:
  # Test C with default configuration
  test-c-default:
    name: Test C Default
    uses: artagon/artagon-workflows/.github/workflows/cmake_c_ci.yml@feature/update-cache-and-sync-ci
    secrets: inherit

  # Test C with C11 standard
  test-c-11:
    name: Test C11
    uses: artagon/artagon-workflows/.github/workflows/cmake_c_ci.yml@feature/update-cache-and-sync-ci
    with:
      c-standard: '11'
    secrets: inherit

  # Test C with C17 standard
  test-c-17:
    name: Test C17
    uses: artagon/artagon-workflows/.github/workflows/cmake_c_ci.yml@feature/update-cache-and-sync-ci
    with:
      c-standard: '17'
    secrets: inherit

  # Test C with C23 standard
  test-c-23:
    name: Test C23
    uses: artagon/artagon-workflows/.github/workflows/cmake_c_ci.yml@feature/update-cache-and-sync-ci
    with:
      c-standard: '23'
    secrets: inherit

  # Test C with custom CMake options
  test-c-custom:
    name: Test C Custom Options
    uses: artagon/artagon-workflows/.github/workflows/cmake_c_ci.yml@feature/update-cache-and-sync-ci
    with:
      c-standard: '17'
      cmake-options: '-DCMAKE_VERBOSE_MAKEFILE=ON'
    secrets: inherit

  # Test C++ with default configuration
  test-cpp-default:
    name: Test C++ Default
    uses: artagon/artagon-workflows/.github/workflows/cmake_cpp_ci.yml@feature/update-cache-and-sync-ci
    secrets: inherit

  # Test C++ with C++17 standard
  test-cpp-17:
    name: Test C++17
    uses: artagon/artagon-workflows/.github/workflows/cmake_cpp_ci.yml@feature/update-cache-and-sync-ci
    with:
      cxx-standard: '17'
    secrets: inherit

  # Test C++ with C++20 standard
  test-cpp-20:
    name: Test C++20
    uses: artagon/artagon-workflows/.github/workflows/cmake_cpp_ci.yml@feature/update-cache-and-sync-ci
    with:
      cxx-standard: '20'
    secrets: inherit

  # Test C++ with C++23 standard
  test-cpp-23:
    name: Test C++23
    uses: artagon/artagon-workflows/.github/workflows/cmake_cpp_ci.yml@feature/update-cache-and-sync-ci
    with:
      cxx-standard: '23'
    secrets: inherit

  # Summary job to check all tests passed
  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [test-c-default, test-c-11, test-c-17, test-c-23, test-c-custom, test-cpp-default, test-cpp-17, test-cpp-20, test-cpp-23]
    if: always()
    steps:
      - name: Check test results
        run: |
          FAILED=false
          for job in test-c-default test-c-11 test-c-17 test-c-23 test-c-custom test-cpp-default test-cpp-17 test-cpp-20 test-cpp-23; do
            result=$(echo '${{ toJSON(needs) }}' | jq -r ".[\"$job\"].result")
            if [ "$result" != "success" ]; then
              echo "❌ $job failed with result: $result"
              FAILED=true
            fi
          done

          if [ "$FAILED" = "true" ]; then
            echo "❌ One or more tests failed"
            exit 1
          else
            echo "✅ All tests passed"
          fi
